//! Export a collection directory as Markdown documentation

use std::path::Path;
use http_parser;

/// Walk a collection root directory and generate Markdown documentation.
/// Each .http file becomes a documented request; folders become sections.
pub fn export_collection_markdown(root: &Path) -> Result<String, String> {
    let collection_name = root
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("API Collection");

    let mut md = String::new();
    md.push_str(&format!("# {}\n\n", collection_name));
    md.push_str(&format!(
        "_Generated by Protide — {}_\n\n",
        chrono::Local::now().format("%Y-%m-%d")
    ));

    collect_dir(root, root, &mut md, 2)?;

    Ok(md)
}

fn collect_dir(
    root: &Path,
    dir: &Path,
    md: &mut String,
    heading_level: usize,
) -> Result<(), String> {
    let mut entries: Vec<std::fs::DirEntry> = std::fs::read_dir(dir)
        .map_err(|e| format!("Cannot read directory {}: {}", dir.display(), e))?
        .filter_map(|e| e.ok())
        .collect();

    entries.sort_by_key(|e| {
        let path = e.path();
        let is_dir = path.is_dir();
        let name = e.file_name().to_string_lossy().to_lowercase();
        (!is_dir, name) // dirs first, then files, alphabetical
    });

    let hashes = "#".repeat(heading_level);

    for entry in entries {
        let path = entry.path();
        let name = entry.file_name().to_string_lossy().to_string();

        // Skip hidden files and non-relevant items
        if name.starts_with('.') {
            continue;
        }

        if path.is_dir() {
            md.push_str(&format!("\n{} {}\n\n", hashes, name));
            collect_dir(root, &path, md, (heading_level + 1).min(6))?;
        } else if path.extension().and_then(|e| e.to_str()) == Some("http")
            && let Ok(content) = std::fs::read_to_string(&path) {
                let request_name = path
                    .file_stem()
                    .and_then(|s| s.to_str())
                    .unwrap_or(&name);
                append_http_request(md, request_name, &content, heading_level);
            }
    }

    Ok(())
}

fn append_http_request(md: &mut String, name: &str, content: &str, heading_level: usize) {
    let requests = match http_parser::parse(content) {
        Ok(r) if !r.is_empty() => r,
        _ => return,
    };

    let hashes = "#".repeat(heading_level);

    for (i, req) in requests.iter().enumerate() {
        let display_name = req.meta.name.as_deref().map(|s| s.to_string()).unwrap_or_else(|| {
            if requests.len() > 1 {
                format!("{} ({})", name, i + 1)
            } else {
                name.to_string()
            }
        });

        md.push_str(&format!("\n{} {}\n\n", hashes, display_name));

        if let Some(desc) = &req.meta.description {
            md.push_str(&format!("{}\n\n", desc));
        }

        md.push_str(&format!("**`{} {}`**\n\n", req.method.as_str(), req.url));

        let enabled_headers: Vec<_> = req.headers.iter().filter(|h| h.enabled).collect();
        if !enabled_headers.is_empty() {
            md.push_str("**Headers**\n\n");
            md.push_str("| Name | Value |\n");
            md.push_str("|------|-------|\n");
            for h in &enabled_headers {
                md.push_str(&format!("| `{}` | `{}` |\n", h.key, h.value));
            }
            md.push('\n');
        }

        if let Some(body) = &req.body {
            let trimmed = body.trim();
            if !trimmed.is_empty() {
                md.push_str("**Request Body**\n\n");
                let lang = detect_body_lang(trimmed);
                md.push_str(&format!("```{}\n{}\n```\n\n", lang, trimmed));
            }
        }

        if let Some(tests) = &req.scripts.tests {
            let trimmed = tests.trim();
            if !trimmed.is_empty() {
                md.push_str("**Test Scripts**\n\n");
                md.push_str(&format!("```javascript\n{}\n```\n\n", trimmed));
            }
        }

        md.push_str("---\n");
    }
}

fn detect_body_lang(body: &str) -> &'static str {
    let trimmed = body.trim();
    if trimmed.starts_with('{') || trimmed.starts_with('[') {
        "json"
    } else if trimmed.starts_with('<') {
        "xml"
    } else {
        "text"
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_detect_body_lang() {
        assert_eq!(detect_body_lang("{\"key\": 1}"), "json");
        assert_eq!(detect_body_lang("[1, 2]"), "json");
        assert_eq!(detect_body_lang("<root/>"), "xml");
        assert_eq!(detect_body_lang("plain text"), "text");
    }

    #[test]
    fn test_scripts_do_not_leak_into_body() {
        let content = r#"
### Login
# @name login

POST https://api.example.com/auth
Content-Type: application/json

{"user": "alice"}

# @tests
expect(response.status).toBe(200);
expect(response.json().token).toBeTruthy();
"#;
        let mut md = String::new();
        append_http_request(&mut md, "login", content, 2);

        // Body section must only contain the JSON payload
        let body_start = md.find("**Request Body**").expect("should have a body section");
        let tests_start = md.find("**Test Scripts**").expect("should have a test scripts section");
        assert!(body_start < tests_start, "body section must come before test scripts section");

        // The text between **Request Body** and **Test Scripts** must not contain expect()
        let body_section = &md[body_start..tests_start];
        assert!(body_section.contains("{\"user\": \"alice\"}"), "body section should contain JSON payload");
        assert!(!body_section.contains("expect("), "expect() must not appear in body section");

        // Test scripts section must contain the assertions
        let tests_section = &md[tests_start..];
        assert!(tests_section.contains("expect(response.status).toBe(200)"), "test scripts must be documented");
    }

    #[test]
    fn test_pre_scripts_excluded_from_body() {
        let content = r#"
POST https://httpbin.org/post
Content-Type: application/json

{"purpose": "demo"}

# @pre-script
const ts = new Date().toISOString();
request.setHeader("X-Timestamp", ts);

# @tests
expect(response.status).toBe(200);
"#;
        let mut md = String::new();
        append_http_request(&mut md, "demo", content, 2);

        assert!(!md.contains("const ts ="), "pre-script must not appear in body section");
        assert!(!md.contains("request.setHeader"), "pre-script must not appear in body section");
        assert!(md.contains("{\"purpose\": \"demo\"}"), "body must contain JSON payload");
    }
}
