//! Export a collection directory as Markdown documentation

use std::path::Path;

/// Walk a collection root directory and generate Markdown documentation.
/// Each .http file becomes a documented request; folders become sections.
pub fn export_collection_markdown(root: &Path) -> Result<String, String> {
    let collection_name = root
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("API Collection");

    let mut md = String::new();
    md.push_str(&format!("# {}\n\n", collection_name));
    md.push_str(&format!(
        "_Generated by Protide — {}_\n\n",
        chrono::Local::now().format("%Y-%m-%d")
    ));

    collect_dir(root, root, &mut md, 2)?;

    Ok(md)
}

fn collect_dir(
    root: &Path,
    dir: &Path,
    md: &mut String,
    heading_level: usize,
) -> Result<(), String> {
    let mut entries: Vec<std::fs::DirEntry> = std::fs::read_dir(dir)
        .map_err(|e| format!("Cannot read directory {}: {}", dir.display(), e))?
        .filter_map(|e| e.ok())
        .collect();

    entries.sort_by_key(|e| {
        let path = e.path();
        let is_dir = path.is_dir();
        let name = e.file_name().to_string_lossy().to_lowercase();
        (!is_dir, name) // dirs first, then files, alphabetical
    });

    let hashes = "#".repeat(heading_level);

    for entry in entries {
        let path = entry.path();
        let name = entry.file_name().to_string_lossy().to_string();

        // Skip hidden files and non-relevant items
        if name.starts_with('.') {
            continue;
        }

        if path.is_dir() {
            md.push_str(&format!("\n{} {}\n\n", hashes, name));
            collect_dir(root, &path, md, (heading_level + 1).min(6))?;
        } else if path.extension().and_then(|e| e.to_str()) == Some("http") {
            if let Ok(content) = std::fs::read_to_string(&path) {
                let request_name = path
                    .file_stem()
                    .and_then(|s| s.to_str())
                    .unwrap_or(&name);
                append_http_request(md, request_name, &content, heading_level);
            }
        }
    }

    Ok(())
}

fn append_http_request(md: &mut String, name: &str, content: &str, heading_level: usize) {
    let hashes = "#".repeat(heading_level);

    // Parse annotations and the request
    let mut display_name = name.to_string();
    let mut description = String::new();
    let mut method = String::new();
    let mut url = String::new();
    let mut headers: Vec<(String, String)> = Vec::new();
    let mut body_lines: Vec<String> = Vec::new();
    let mut in_body = false;

    for line in content.lines() {
        let trimmed = line.trim();

        // Annotations
        if let Some(val) = trimmed.strip_prefix("# @name ") {
            display_name = val.to_string();
            continue;
        }
        if let Some(val) = trimmed.strip_prefix("# @description ") {
            description = val.to_string();
            continue;
        }
        if trimmed.starts_with("# ") || trimmed == "#" {
            continue; // skip other comments
        }

        // Empty line = start/end of body section
        if trimmed.is_empty() {
            if !method.is_empty() && !in_body {
                in_body = true;
            }
            continue;
        }

        // Request line: METHOD URL [HTTP_VERSION]
        if method.is_empty() && !trimmed.starts_with('#') {
            let parts: Vec<&str> = trimmed.splitn(3, ' ').collect();
            if let Some(&m) = parts.first() {
                let upper = m.to_uppercase();
                if matches!(
                    upper.as_str(),
                    "GET" | "POST" | "PUT" | "DELETE" | "PATCH" | "HEAD" | "OPTIONS"
                ) {
                    method = upper;
                    url = parts.get(1).copied().unwrap_or("").to_string();
                    continue;
                }
            }
        }

        // Headers
        if !method.is_empty() && !in_body && trimmed.contains(':') {
            if let Some((k, v)) = trimmed.split_once(':') {
                headers.push((k.trim().to_string(), v.trim().to_string()));
            }
            continue;
        }

        // Body
        if in_body {
            body_lines.push(line.to_string());
        }
    }

    if method.is_empty() {
        return;
    }

    md.push_str(&format!("\n{} {}\n\n", hashes, display_name));

    if !description.is_empty() {
        md.push_str(&format!("{}\n\n", description));
    }

    // Method + URL line
    md.push_str(&format!("**`{} {}`**\n\n", method, url));

    // Headers table
    if !headers.is_empty() {
        md.push_str("**Headers**\n\n");
        md.push_str("| Name | Value |\n");
        md.push_str("|------|-------|\n");
        for (k, v) in &headers {
            md.push_str(&format!("| `{}` | `{}` |\n", k, v));
        }
        md.push('\n');
    }

    // Body
    let body = body_lines.join("\n").trim().to_string();
    if !body.is_empty() {
        md.push_str("**Request Body**\n\n");
        let lang = detect_body_lang(&body);
        md.push_str(&format!("```{}\n{}\n```\n\n", lang, body));
    }

    md.push_str("---\n");
}

fn detect_body_lang(body: &str) -> &'static str {
    let trimmed = body.trim();
    if trimmed.starts_with('{') || trimmed.starts_with('[') {
        "json"
    } else if trimmed.starts_with('<') {
        "xml"
    } else {
        "text"
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_detect_body_lang() {
        assert_eq!(detect_body_lang("{\"key\": 1}"), "json");
        assert_eq!(detect_body_lang("[1, 2]"), "json");
        assert_eq!(detect_body_lang("<root/>"), "xml");
        assert_eq!(detect_body_lang("plain text"), "text");
    }
}
